config/routes.rb
Dms::Application.routes.draw do

	get '/user/accessible_org'	=> 'accounts#accessible_org'
  get "/admin/download_error_docs" => "admin#get_error_docs"
  get "/admin/download_storge_rate" => "admin#get_storge_rate"

  get "/org_info/update_data" => "dictionary_info#update_data"
  get "/get_user_info" => "accounts#get_user_info"
  get "org_info/index"
  get "/org_info" => "OrgInfo#index"
  post "/org_info/create" => "OrgInfo#create"
  put "/org_info/update" => "OrgInfo#update"
  delete "/org_info/delete" => "OrgInfo#destroy"

  get "/agency_select" => "business_agency_maintain#get_select"
  get "/agency_list" => "business_agency_maintain#index"
  post "/agency_create" => "business_agency_maintain#create"
  post "/agency_update" => "business_agency_maintain#update_data"
  delete "/agency_delete" => "business_agency_maintain#destroy"

  get "/user_select" => "accounts#user_select"
  match "/eir_business_process/:id" => "eir_business_process#delete_interchange_receipt", :via => :delete
  post "/interchange_receipt/list" => "eir_business_process#interchange_receipt_list"
  post "/eir_business_process" => "eir_business_process#business_process"
  post "/admin/upload_org" => "dictionary_info#upload_org"
  get "/admin/org_for_doc" => "admin#org_for_doc"
  get "/admin/get_org" => "admin#get_org"
  get "/documents/test" => "documents#index_paging"
  get "/requisition_print" =>  "requisition#print"
  get "/filter_docs" => "requisition#filter_docs"
  get "/filter_org" => "requisition#filter_org"
  post "/requisitions" => "requisition#create_requisition"
  post "/lending_statistics_list" => "requisition#lending_statistics_list"
  get "/requisitions" => "requisition#requisitions"
  post "/requisitions/change_status" => "requisition#change_status"
  post "/find_log" => "settings#find_log"

  post "/system_log" => "settings#system_log"
  post "/query_log" => "settings#query_log"
  post "/document_log" => "settings#document_log"

  post "/admin/import_dictionary" => "dictionary_info#import_dictionary"

  get "/admin/dictionary" => "admin#dictionary"
  get "dictionary_info/update_dictionary" => "dictionary_info#update_dictionary"
  get "dictionary_info/get_dictionary" => "dictionary_info#get_dictionary"

  post "/documents/all_print_doc" => "documents#all_print_doc"
  post "/documents/all_print" => "documents#all_print"

  get '/find_doc_comments' => 'comments#find_doc_commit'

  get 'set_dialog' => 'settings#set_dialog'

  get 'get_dialog' => 'settings#get_dialog'

  get "/admin/show_docs" => "admin#show_docs"

  post "/comments/commit" => "comments#commit"
  post "/comments/pagetype" => "comments#create_page_type"
  post "/comments/delete_pagetype" => "comments#delete_page_type"
  get "/comments/get" => "comments#get"

  post "/admin/system" => "admin#upload_package_system"

  get "/admin/log_index" => "admin#log_index"

  get "/admin/clear_log" => "admin#clear_log"

  get "/admin/download_log" => "admin#download_log"

  post "/admin/change_password" => "admin#change_password"

  get "/admin/update_password" => "admin#update_password"
  
  get "admin/update_system" => "admin#update_system"

  resources :admin

  post '/upload_user' => "upload_file#system_upload"

  get "/get_son_table" => "search_condition#get_son_table"

  get "/search_condition" => "search_condition#search_condition"

  resources :normal_import_price_less_records

  post "/upload_file" => "upload_file#import_excel"

  resources :zero_find_check_infos

  resources :import_most_time_org_doc_infos

  post "/search_result/excle" => "operate_data#export_search"
  post "/status/zip_files" => "queries_controller#zip_files_status"

  post "/generateExcel" => "operate_data#export_data"

  post "/settings/update" => "settings#sys_setting"
  get "/settings" => "settings#index"

  post "/users/isLocked" => "accounts#isUserLocked"
  post "/exportChart" => "monitoring_data#exportToPNG"

  devise_for :users , :controllers => { :sessions => "test/sessions"},:path_names => { :sign_in => 'login', :sign_out => 'logout' }

  match "/print/printpdf" => "documents#print_doc"
  post "/documents/pending_modified" => "documents#stats_export"
  post "/monitoring/query" => "monitoring_data#get_json"
  post "/monitoring/query_util" => "monitoring_data#get_util"

  resources :query_histories

  resources :special_documents
  resources :modified_documents
  resources :doc_groups

  resources :documents do
    collection do
      post 'multi_query'
      post 'search_docs'
      post 'by_doc_source'
      post 'inquire'
      post 'checkout'
    end
  end

  resources :folders

  resources :web_links

  resources :roles

  get "/a" => "welcome#login_admin"
  root :to => 'welcome#welcome'

  match "/api/query" => "queries#api_query", :via => :post
  match "/api/query_status" => "queries#api_get_status", :via => :post

  match "/docs/:doc_id" => "documents#query", :constraints => { :doc_id => /\d{18}/ } 
  match "/special_docs/:doc_id" => "modified_documents#query", :constraints => { :doc_id => /\d{18}/ } 
  match "/api/docs/:doc_id" => "documents#api_query", :constraints => { :doc_id => /\d{18}/ } 

  match "/docs/print" => "documents#print"
  match "/docs/testify" => "documents#testify"

  match "/root/docimages/:a/:b/" => "welcome#img"
  post "/qh/u" => "query_histories#byuser"
  match "/qh/d/:doc_id" => "query_histories#bydoc"
  match "/qh_all" => "query_histories#show_all"

  get "/qh/quota" => "query_histories#over_quota"

  post "/qh/query_search" => "query_histories#search"
  post "/dh/query_search" => "document_histories#search"

  get "/doc_source/all" => "documents#list_doc_sources"

  post "/document_histories/dh_report" => "document_histories#dh_report"
  match "/document_histories/dh_special" => "document_histories#dh_special"

  match "/document_histories/query/:gid" => "query_histories#query_by_group"

  match "/accounts" => "accounts#index", :via => :get
  match "/accounts" => "accounts#newuser", :via => :post
  match "/accounts/:id" => "accounts#update", :via => :put
  match "/accounts/:id" => "accounts#destroy", :via => :delete
  match "/accounts/get_links" => "accounts#get_links"
  match "/accounts/chpwd" => "accounts#change_password", :via => :post

  post "/accounts/roles/edit/:id" => "roles#update_role"

end

app/models/zero_find_check_info.rb
class ZeroFindCheckInfo < ActiveRecord::Base
end

app/controllers/zero_find_check_infos_controller.rb
class ZeroFindCheckInfosController < ApplicationController
  # GET /zero_find_check_infos
  # GET /zero_find_check_infos.json
  def index
    @zero_find_check_infos = ZeroFindCheckInfo.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @zero_find_check_infos }
    end
  end

  # GET /zero_find_check_infos/1
  # GET /zero_find_check_infos/1.json
  def show
    @zero_find_check_info = ZeroFindCheckInfo.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @zero_find_check_info }
    end
  end

  # GET /zero_find_check_infos/new
  # GET /zero_find_check_infos/new.json
  def new
    @zero_find_check_info = ZeroFindCheckInfo.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @zero_find_check_info }
    end
  end

  # GET /zero_find_check_infos/1/edit
  def edit
    @zero_find_check_info = ZeroFindCheckInfo.find(params[:id])
  end

  # POST /zero_find_check_infos
  # POST /zero_find_check_infos.json
  def create
    @zero_find_check_info = ZeroFindCheckInfo.new(params[:zero_find_check_info])

    respond_to do |format|
      if @zero_find_check_info.save
        format.html { redirect_to @zero_find_check_info, notice: 'Zero find check info was successfully created.' }
        format.json { render json: @zero_find_check_info, status: :created, location: @zero_find_check_info }
      else
        format.html { render action: "new" }
        format.json { render json: @zero_find_check_info.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /zero_find_check_infos/1
  # PUT /zero_find_check_infos/1.json
  def update
    @zero_find_check_info = ZeroFindCheckInfo.find(params[:id])

    respond_to do |format|
      if @zero_find_check_info.update_attributes(params[:zero_find_check_info])
        format.html { redirect_to @zero_find_check_info, notice: 'Zero find check info was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @zero_find_check_info.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /zero_find_check_infos/1
  # DELETE /zero_find_check_infos/1.json
  def destroy
    @zero_find_check_info = ZeroFindCheckInfo.find(params[:id])
    @zero_find_check_info.destroy

    respond_to do |format|
      format.html { redirect_to zero_find_check_infos_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/zero_find_check_infos_helper.rb
module ZeroFindCheckInfosHelper
end

app/views/zero_find_check_infos/_form.html.erb
<%= form_for(@zero_find_check_info) do |f| %>
  <% if @zero_find_check_info.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@zero_find_check_info.errors.count, "error") %> prohibited this zero_find_check_info from being saved:</h2>

      <ul>
      <% @zero_find_check_info.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :business_units_number %><br />
    <%= f.text_field :business_units_number %>
  </div>
  <div class="field">
    <%= f.label :operating_name %><br />
    <%= f.text_field :operating_name %>
  </div>
  <div class="field">
    <%= f.label :number_import_export_declarations %><br />
    <%= f.number_field :number_import_export_declarations %>
  </div>
  <div class="field">
    <%= f.label :number_import_export_inspection %><br />
    <%= f.number_field :number_import_export_inspection %>
  </div>
  <div class="field">
    <%= f.label :import_export_inspection_rate %><br />
    <%= f.text_field :import_export_inspection_rate %>
  </div>
  <div class="field">
    <%= f.label :declarations_number %><br />
    <%= f.text_field :declarations_number %>
  </div>
  <div class="field">
    <%= f.label :import_export %><br />
    <%= f.text_field :import_export %>
  </div>
  <div class="field">
    <%= f.label :examination_handling_results %><br />
    <%= f.text_field :examination_handling_results %>
  </div>
  <div class="field">
    <%= f.label :declaration_customs %><br />
    <%= f.text_field :declaration_customs %>
  </div>
  <div class="field">
    <%= f.label :date_value %><br />
    <%= f.datetime_select :date_value %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/zero_find_check_infos/edit.html.erb
<h1>Editing zero_find_check_info</h1>

<%= render 'form' %>

<%= link_to 'Show', @zero_find_check_info %> |
<%= link_to 'Back', zero_find_check_infos_path %>

app/views/zero_find_check_infos/index.html.erb
<h1>Listing zero_find_check_infos</h1>

<table>
  <tr>
    <th>Business units number</th>
    <th>Operating name</th>
    <th>Number import export declarations</th>
    <th>Number import export inspection</th>
    <th>Import export inspection rate</th>
    <th>Declarations number</th>
    <th>Import export</th>
    <th>Examination handling results</th>
    <th>Declaration customs</th>
    <th>Date value</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @zero_find_check_infos.each do |zero_find_check_info| %>
  <tr>
    <td><%= zero_find_check_info.business_units_number %></td>
    <td><%= zero_find_check_info.operating_name %></td>
    <td><%= zero_find_check_info.number_import_export_declarations %></td>
    <td><%= zero_find_check_info.number_import_export_inspection %></td>
    <td><%= zero_find_check_info.import_export_inspection_rate %></td>
    <td><%= zero_find_check_info.declarations_number %></td>
    <td><%= zero_find_check_info.import_export %></td>
    <td><%= zero_find_check_info.examination_handling_results %></td>
    <td><%= zero_find_check_info.declaration_customs %></td>
    <td><%= zero_find_check_info.date_value %></td>
    <td><%= link_to 'Show', zero_find_check_info %></td>
    <td><%= link_to 'Edit', edit_zero_find_check_info_path(zero_find_check_info) %></td>
    <td><%= link_to 'Destroy', zero_find_check_info, confirm: 'Are you sure?', method: :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Zero find check info', new_zero_find_check_info_path %>

app/views/zero_find_check_infos/new.html.erb
<h1>New zero_find_check_info</h1>

<%= render 'form' %>

<%= link_to 'Back', zero_find_check_infos_path %>

app/views/zero_find_check_infos/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Business units number:</b>
  <%= @zero_find_check_info.business_units_number %>
</p>

<p>
  <b>Operating name:</b>
  <%= @zero_find_check_info.operating_name %>
</p>

<p>
  <b>Number import export declarations:</b>
  <%= @zero_find_check_info.number_import_export_declarations %>
</p>

<p>
  <b>Number import export inspection:</b>
  <%= @zero_find_check_info.number_import_export_inspection %>
</p>

<p>
  <b>Import export inspection rate:</b>
  <%= @zero_find_check_info.import_export_inspection_rate %>
</p>

<p>
  <b>Declarations number:</b>
  <%= @zero_find_check_info.declarations_number %>
</p>

<p>
  <b>Import export:</b>
  <%= @zero_find_check_info.import_export %>
</p>

<p>
  <b>Examination handling results:</b>
  <%= @zero_find_check_info.examination_handling_results %>
</p>

<p>
  <b>Declaration customs:</b>
  <%= @zero_find_check_info.declaration_customs %>
</p>

<p>
  <b>Date value:</b>
  <%= @zero_find_check_info.date_value %>
</p>


<%= link_to 'Edit', edit_zero_find_check_info_path(@zero_find_check_info) %> |
<%= link_to 'Back', zero_find_check_infos_path %>