config/routes.rb
Dms::Application.routes.draw do

	get '/user/accessible_org'	=> 'accounts#accessible_org'
  get "/admin/download_error_docs" => "admin#get_error_docs"
  get "/admin/download_storge_rate" => "admin#get_storge_rate"

  get "/org_info/update_data" => "dictionary_info#update_data"
  get "/get_user_info" => "accounts#get_user_info"
  get "org_info/index"
  get "/org_info" => "OrgInfo#index"
  post "/org_info/create" => "OrgInfo#create"
  put "/org_info/update" => "OrgInfo#update"
  delete "/org_info/delete" => "OrgInfo#destroy"

  get "/agency_select" => "business_agency_maintain#get_select"
  get "/agency_list" => "business_agency_maintain#index"
  post "/agency_create" => "business_agency_maintain#create"
  post "/agency_update" => "business_agency_maintain#update_data"
  delete "/agency_delete" => "business_agency_maintain#destroy"

  get "/user_select" => "accounts#user_select"
  match "/eir_business_process/:id" => "eir_business_process#delete_interchange_receipt", :via => :delete
  post "/interchange_receipt/list" => "eir_business_process#interchange_receipt_list"
  post "/eir_business_process" => "eir_business_process#business_process"
  post "/admin/upload_org" => "dictionary_info#upload_org"
  get "/admin/org_for_doc" => "admin#org_for_doc"
  get "/admin/get_org" => "admin#get_org"
  get "/documents/test" => "documents#index_paging"
  get "/requisition_print" =>  "requisition#print"
  get "/filter_docs" => "requisition#filter_docs"
  get "/filter_org" => "requisition#filter_org"
  post "/requisitions" => "requisition#create_requisition"
  post "/lending_statistics_list" => "requisition#lending_statistics_list"
  get "/requisitions" => "requisition#requisitions"
  post "/requisitions/change_status" => "requisition#change_status"
  post "/find_log" => "settings#find_log"

  post "/system_log" => "settings#system_log"
  post "/query_log" => "settings#query_log"
  post "/document_log" => "settings#document_log"

  post "/admin/import_dictionary" => "dictionary_info#import_dictionary"

  get "/admin/dictionary" => "admin#dictionary"
  get "dictionary_info/update_dictionary" => "dictionary_info#update_dictionary"
  get "dictionary_info/get_dictionary" => "dictionary_info#get_dictionary"

  post "/documents/all_print_doc" => "documents#all_print_doc"
  post "/documents/all_print" => "documents#all_print"

  get '/find_doc_comments' => 'comments#find_doc_commit'

  get 'set_dialog' => 'settings#set_dialog'

  get 'get_dialog' => 'settings#get_dialog'

  get "/admin/show_docs" => "admin#show_docs"

  post "/comments/commit" => "comments#commit"
  post "/comments/pagetype" => "comments#create_page_type"
  post "/comments/delete_pagetype" => "comments#delete_page_type"
  get "/comments/get" => "comments#get"

  post "/admin/system" => "admin#upload_package_system"

  get "/admin/log_index" => "admin#log_index"

  get "/admin/clear_log" => "admin#clear_log"

  get "/admin/download_log" => "admin#download_log"

  post "/admin/change_password" => "admin#change_password"

  get "/admin/update_password" => "admin#update_password"
  
  get "admin/update_system" => "admin#update_system"

  resources :admin

  post '/upload_user' => "upload_file#system_upload"

  get "/get_son_table" => "search_condition#get_son_table"

  get "/search_condition" => "search_condition#search_condition"

  resources :normal_import_price_less_records

  post "/upload_file" => "upload_file#import_excel"

  resources :zero_find_check_infos

  resources :import_most_time_org_doc_infos

  post "/search_result/excle" => "operate_data#export_search"
  post "/status/zip_files" => "queries_controller#zip_files_status"

  post "/generateExcel" => "operate_data#export_data"

  post "/settings/update" => "settings#sys_setting"
  get "/settings" => "settings#index"

  post "/users/isLocked" => "accounts#isUserLocked"
  post "/exportChart" => "monitoring_data#exportToPNG"

  devise_for :users , :controllers => { :sessions => "test/sessions"},:path_names => { :sign_in => 'login', :sign_out => 'logout' }

  match "/print/printpdf" => "documents#print_doc"
  post "/documents/pending_modified" => "documents#stats_export"
  post "/monitoring/query" => "monitoring_data#get_json"
  post "/monitoring/query_util" => "monitoring_data#get_util"

  resources :query_histories

  resources :special_documents
  resources :modified_documents
  resources :doc_groups

  resources :documents do
    collection do
      post 'multi_query'
      post 'search_docs'
      post 'by_doc_source'
      post 'inquire'
      post 'checkout'
    end
  end

  resources :folders

  resources :web_links

  resources :roles

  get "/a" => "welcome#login_admin"
  root :to => 'welcome#welcome'

  match "/api/query" => "queries#api_query", :via => :post
  match "/api/query_status" => "queries#api_get_status", :via => :post

  match "/docs/:doc_id" => "documents#query", :constraints => { :doc_id => /\d{18}/ } 
  match "/special_docs/:doc_id" => "modified_documents#query", :constraints => { :doc_id => /\d{18}/ } 
  match "/api/docs/:doc_id" => "documents#api_query", :constraints => { :doc_id => /\d{18}/ } 

  match "/docs/print" => "documents#print"
  match "/docs/testify" => "documents#testify"

  match "/root/docimages/:a/:b/" => "welcome#img"
  post "/qh/u" => "query_histories#byuser"
  match "/qh/d/:doc_id" => "query_histories#bydoc"
  match "/qh_all" => "query_histories#show_all"

  get "/qh/quota" => "query_histories#over_quota"

  post "/qh/query_search" => "query_histories#search"
  post "/dh/query_search" => "document_histories#search"

  get "/doc_source/all" => "documents#list_doc_sources"

  post "/document_histories/dh_report" => "document_histories#dh_report"
  match "/document_histories/dh_special" => "document_histories#dh_special"

  match "/document_histories/query/:gid" => "query_histories#query_by_group"

  match "/accounts" => "accounts#index", :via => :get
  match "/accounts" => "accounts#newuser", :via => :post
  match "/accounts/:id" => "accounts#update", :via => :put
  match "/accounts/:id" => "accounts#destroy", :via => :delete
  match "/accounts/get_links" => "accounts#get_links"
  match "/accounts/chpwd" => "accounts#change_password", :via => :post

  post "/accounts/roles/edit/:id" => "roles#update_role"

end

app/models/import_most_time_org_doc_info.rb
class ImportMostTimeOrgDocInfo < ActiveRecord::Base
end

app/controllers/import_most_time_org_doc_infos_controller.rb
class ImportMostTimeOrgDocInfosController < ApplicationController
  # GET /import_most_time_org_doc_infos
  # GET /import_most_time_org_doc_infos.json
  def index
    @import_most_time_org_doc_infos = ImportMostTimeOrgDocInfo.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @import_most_time_org_doc_infos }
    end
  end

  # GET /import_most_time_org_doc_infos/1
  # GET /import_most_time_org_doc_infos/1.json
  def show
    @import_most_time_org_doc_info = ImportMostTimeOrgDocInfo.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @import_most_time_org_doc_info }
    end
  end

  # GET /import_most_time_org_doc_infos/new
  # GET /import_most_time_org_doc_infos/new.json
  def new
    @import_most_time_org_doc_info = ImportMostTimeOrgDocInfo.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @import_most_time_org_doc_info }
    end
  end

  # GET /import_most_time_org_doc_infos/1/edit
  def edit
    @import_most_time_org_doc_info = ImportMostTimeOrgDocInfo.find(params[:id])
  end

  # POST /import_most_time_org_doc_infos
  # POST /import_most_time_org_doc_infos.json
  def create
    @import_most_time_org_doc_info = ImportMostTimeOrgDocInfo.new(params[:import_most_time_org_doc_info])

    respond_to do |format|
      if @import_most_time_org_doc_info.save
        format.html { redirect_to @import_most_time_org_doc_info, notice: 'Import most time org doc info was successfully created.' }
        format.json { render json: @import_most_time_org_doc_info, status: :created, location: @import_most_time_org_doc_info }
      else
        format.html { render action: "new" }
        format.json { render json: @import_most_time_org_doc_info.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /import_most_time_org_doc_infos/1
  # PUT /import_most_time_org_doc_infos/1.json
  def update
    @import_most_time_org_doc_info = ImportMostTimeOrgDocInfo.find(params[:id])

    respond_to do |format|
      if @import_most_time_org_doc_info.update_attributes(params[:import_most_time_org_doc_info])
        format.html { redirect_to @import_most_time_org_doc_info, notice: 'Import most time org doc info was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @import_most_time_org_doc_info.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /import_most_time_org_doc_infos/1
  # DELETE /import_most_time_org_doc_infos/1.json
  def destroy
    @import_most_time_org_doc_info = ImportMostTimeOrgDocInfo.find(params[:id])
    @import_most_time_org_doc_info.destroy

    respond_to do |format|
      format.html { redirect_to import_most_time_org_doc_infos_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/import_most_time_org_doc_infos_helper.rb
module ImportMostTimeOrgDocInfosHelper
end

app/views/import_most_time_org_doc_infos/_form.html.erb
<%= form_for(@import_most_time_org_doc_info) do |f| %>
  <% if @import_most_time_org_doc_info.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@import_most_time_org_doc_info.errors.count, "error") %> prohibited this import_most_time_org_doc_info from being saved:</h2>

      <ul>
      <% @import_most_time_org_doc_info.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :declarations_number %><br />
    <%= f.text_field :declarations_number %>
  </div>
  <div class="field">
    <%= f.label :mode_transport %><br />
    <%= f.text_field :mode_transport %>
  </div>
  <div class="field">
    <%= f.label :release_time %><br />
    <%= f.datetime_select :release_time %>
  </div>
  <div class="field">
    <%= f.label :accept_declaration_time %><br />
    <%= f.datetime_select :accept_declaration_time %>
  </div>
  <div class="field">
    <%= f.label :overall_operating_hours_hours %><br />
    <%= f.text_field :overall_operating_hours_hours %>
  </div>
  <div class="field">
    <%= f.label :declaration_customs_code %><br />
    <%= f.text_field :declaration_customs_code %>
  </div>
  <div class="field">
    <%= f.label :declaration_customs %><br />
    <%= f.text_field :declaration_customs %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/import_most_time_org_doc_infos/edit.html.erb
<h1>Editing import_most_time_org_doc_info</h1>

<%= render 'form' %>

<%= link_to 'Show', @import_most_time_org_doc_info %> |
<%= link_to 'Back', import_most_time_org_doc_infos_path %>

app/views/import_most_time_org_doc_infos/index.html.erb
<h1>Listing import_most_time_org_doc_infos</h1>

<table>
  <tr>
    <th>Declarations number</th>
    <th>Mode transport</th>
    <th>Release time</th>
    <th>Accept declaration time</th>
    <th>Overall operating hours hours</th>
    <th>Declaration customs code</th>
    <th>Declaration customs</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @import_most_time_org_doc_infos.each do |import_most_time_org_doc_info| %>
  <tr>
    <td><%= import_most_time_org_doc_info.declarations_number %></td>
    <td><%= import_most_time_org_doc_info.mode_transport %></td>
    <td><%= import_most_time_org_doc_info.release_time %></td>
    <td><%= import_most_time_org_doc_info.accept_declaration_time %></td>
    <td><%= import_most_time_org_doc_info.overall_operating_hours_hours %></td>
    <td><%= import_most_time_org_doc_info.declaration_customs_code %></td>
    <td><%= import_most_time_org_doc_info.declaration_customs %></td>
    <td><%= link_to 'Show', import_most_time_org_doc_info %></td>
    <td><%= link_to 'Edit', edit_import_most_time_org_doc_info_path(import_most_time_org_doc_info) %></td>
    <td><%= link_to 'Destroy', import_most_time_org_doc_info, confirm: 'Are you sure?', method: :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Import most time org doc info', new_import_most_time_org_doc_info_path %>

app/views/import_most_time_org_doc_infos/new.html.erb
<h1>New import_most_time_org_doc_info</h1>

<%= render 'form' %>

<%= link_to 'Back', import_most_time_org_doc_infos_path %>

app/views/import_most_time_org_doc_infos/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Declarations number:</b>
  <%= @import_most_time_org_doc_info.declarations_number %>
</p>

<p>
  <b>Mode transport:</b>
  <%= @import_most_time_org_doc_info.mode_transport %>
</p>

<p>
  <b>Release time:</b>
  <%= @import_most_time_org_doc_info.release_time %>
</p>

<p>
  <b>Accept declaration time:</b>
  <%= @import_most_time_org_doc_info.accept_declaration_time %>
</p>

<p>
  <b>Overall operating hours hours:</b>
  <%= @import_most_time_org_doc_info.overall_operating_hours_hours %>
</p>

<p>
  <b>Declaration customs code:</b>
  <%= @import_most_time_org_doc_info.declaration_customs_code %>
</p>

<p>
  <b>Declaration customs:</b>
  <%= @import_most_time_org_doc_info.declaration_customs %>
</p>


<%= link_to 'Edit', edit_import_most_time_org_doc_info_path(@import_most_time_org_doc_info) %> |
<%= link_to 'Back', import_most_time_org_doc_infos_path %>