config/routes.rb
Dms::Application.routes.draw do

	get '/user/accessible_org'	=> 'accounts#accessible_org'
  get "/admin/download_error_docs" => "admin#get_error_docs"
  get "/admin/download_storge_rate" => "admin#get_storge_rate"

  get "/org_info/update_data" => "dictionary_info#update_data"
  get "/get_user_info" => "accounts#get_user_info"
  get "org_info/index"
  get "/org_info" => "OrgInfo#index"
  post "/org_info/create" => "OrgInfo#create"
  put "/org_info/update" => "OrgInfo#update"
  delete "/org_info/delete" => "OrgInfo#destroy"

  get "/agency_select" => "business_agency_maintain#get_select"
  get "/agency_list" => "business_agency_maintain#index"
  post "/agency_create" => "business_agency_maintain#create"
  post "/agency_update" => "business_agency_maintain#update_data"
  delete "/agency_delete" => "business_agency_maintain#destroy"

  get "/user_select" => "accounts#user_select"
  match "/eir_business_process/:id" => "eir_business_process#delete_interchange_receipt", :via => :delete
  post "/interchange_receipt/list" => "eir_business_process#interchange_receipt_list"
  post "/eir_business_process" => "eir_business_process#business_process"
  post "/admin/upload_org" => "dictionary_info#upload_org"
  get "/admin/org_for_doc" => "admin#org_for_doc"
  get "/admin/get_org" => "admin#get_org"
  get "/documents/test" => "documents#index_paging"
  get "/requisition_print" =>  "requisition#print"
  get "/filter_docs" => "requisition#filter_docs"
  get "/filter_org" => "requisition#filter_org"
  post "/requisitions" => "requisition#create_requisition"
  post "/lending_statistics_list" => "requisition#lending_statistics_list"
  get "/requisitions" => "requisition#requisitions"
  post "/requisitions/change_status" => "requisition#change_status"
  post "/find_log" => "settings#find_log"

  post "/system_log" => "settings#system_log"
  post "/query_log" => "settings#query_log"
  post "/document_log" => "settings#document_log"

  post "/admin/import_dictionary" => "dictionary_info#import_dictionary"

  get "/admin/dictionary" => "admin#dictionary"
  get "dictionary_info/update_dictionary" => "dictionary_info#update_dictionary"
  get "dictionary_info/get_dictionary" => "dictionary_info#get_dictionary"

  post "/documents/all_print_doc" => "documents#all_print_doc"
  post "/documents/all_print" => "documents#all_print"

  get '/find_doc_comments' => 'comments#find_doc_commit'

  get 'set_dialog' => 'settings#set_dialog'

  get 'get_dialog' => 'settings#get_dialog'

  get "/admin/show_docs" => "admin#show_docs"

  post "/comments/commit" => "comments#commit"
  post "/comments/pagetype" => "comments#create_page_type"
  post "/comments/delete_pagetype" => "comments#delete_page_type"
  get "/comments/get" => "comments#get"

  post "/admin/system" => "admin#upload_package_system"

  get "/admin/log_index" => "admin#log_index"

  get "/admin/clear_log" => "admin#clear_log"

  get "/admin/download_log" => "admin#download_log"

  post "/admin/change_password" => "admin#change_password"

  get "/admin/update_password" => "admin#update_password"
  
  get "admin/update_system" => "admin#update_system"

  resources :admin

  post '/upload_user' => "upload_file#system_upload"

  get "/get_son_table" => "search_condition#get_son_table"

  get "/search_condition" => "search_condition#search_condition"

  resources :normal_import_price_less_records

  post "/upload_file" => "upload_file#import_excel"

  resources :zero_find_check_infos

  resources :import_most_time_org_doc_infos

  post "/search_result/excle" => "operate_data#export_search"
  post "/status/zip_files" => "queries_controller#zip_files_status"

  post "/generateExcel" => "operate_data#export_data"

  post "/settings/update" => "settings#sys_setting"
  get "/settings" => "settings#index"

  post "/users/isLocked" => "accounts#isUserLocked"
  post "/exportChart" => "monitoring_data#exportToPNG"

  devise_for :users , :controllers => { :sessions => "test/sessions"},:path_names => { :sign_in => 'login', :sign_out => 'logout' }

  match "/print/printpdf" => "documents#print_doc"
  post "/documents/pending_modified" => "documents#stats_export"
  post "/monitoring/query" => "monitoring_data#get_json"
  post "/monitoring/query_util" => "monitoring_data#get_util"

  resources :query_histories

  resources :special_documents
  resources :modified_documents
  resources :doc_groups

  resources :documents do
    collection do
      post 'multi_query'
      post 'search_docs'
      post 'by_doc_source'
      post 'inquire'
      post 'checkout'
    end
  end

  resources :folders

  resources :web_links

  resources :roles

  get "/a" => "welcome#login_admin"
  root :to => 'welcome#welcome'

  match "/api/query" => "queries#api_query", :via => :post
  match "/api/query_status" => "queries#api_get_status", :via => :post

  match "/docs/:doc_id" => "documents#query", :constraints => { :doc_id => /\d{18}/ } 
  match "/special_docs/:doc_id" => "modified_documents#query", :constraints => { :doc_id => /\d{18}/ } 
  match "/api/docs/:doc_id" => "documents#api_query", :constraints => { :doc_id => /\d{18}/ } 

  match "/docs/print" => "documents#print"
  match "/docs/testify" => "documents#testify"

  match "/root/docimages/:a/:b/" => "welcome#img"
  post "/qh/u" => "query_histories#byuser"
  match "/qh/d/:doc_id" => "query_histories#bydoc"
  match "/qh_all" => "query_histories#show_all"

  get "/qh/quota" => "query_histories#over_quota"

  post "/qh/query_search" => "query_histories#search"
  post "/dh/query_search" => "document_histories#search"

  get "/doc_source/all" => "documents#list_doc_sources"

  post "/document_histories/dh_report" => "document_histories#dh_report"
  match "/document_histories/dh_special" => "document_histories#dh_special"

  match "/document_histories/query/:gid" => "query_histories#query_by_group"

  match "/accounts" => "accounts#index", :via => :get
  match "/accounts" => "accounts#newuser", :via => :post
  match "/accounts/:id" => "accounts#update", :via => :put
  match "/accounts/:id" => "accounts#destroy", :via => :delete
  match "/accounts/get_links" => "accounts#get_links"
  match "/accounts/chpwd" => "accounts#change_password", :via => :post

  post "/accounts/roles/edit/:id" => "roles#update_role"

end

app/models/normal_import_price_less_record.rb
class NormalImportPriceLessRecord < ActiveRecord::Base
end

app/controllers/normal_import_price_less_records_controller.rb
class NormalImportPriceLessRecordsController < ApplicationController
  # GET /normal_import_price_less_records
  # GET /normal_import_price_less_records.json
  def index
    @normal_import_price_less_records = NormalImportPriceLessRecord.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @normal_import_price_less_records }
    end
  end

  # GET /normal_import_price_less_records/1
  # GET /normal_import_price_less_records/1.json
  def show
    @normal_import_price_less_record = NormalImportPriceLessRecord.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @normal_import_price_less_record }
    end
  end

  # GET /normal_import_price_less_records/new
  # GET /normal_import_price_less_records/new.json
  def new
    @normal_import_price_less_record = NormalImportPriceLessRecord.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @normal_import_price_less_record }
    end
  end

  # GET /normal_import_price_less_records/1/edit
  def edit
    @normal_import_price_less_record = NormalImportPriceLessRecord.find(params[:id])
  end

  # POST /normal_import_price_less_records
  # POST /normal_import_price_less_records.json
  def create
    @normal_import_price_less_record = NormalImportPriceLessRecord.new(params[:normal_import_price_less_record])

    respond_to do |format|
      if @normal_import_price_less_record.save
        format.html { redirect_to @normal_import_price_less_record, notice: 'Normal import price less record was successfully created.' }
        format.json { render json: @normal_import_price_less_record, status: :created, location: @normal_import_price_less_record }
      else
        format.html { render action: "new" }
        format.json { render json: @normal_import_price_less_record.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /normal_import_price_less_records/1
  # PUT /normal_import_price_less_records/1.json
  def update
    @normal_import_price_less_record = NormalImportPriceLessRecord.find(params[:id])

    respond_to do |format|
      if @normal_import_price_less_record.update_attributes(params[:normal_import_price_less_record])
        format.html { redirect_to @normal_import_price_less_record, notice: 'Normal import price less record was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @normal_import_price_less_record.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /normal_import_price_less_records/1
  # DELETE /normal_import_price_less_records/1.json
  def destroy
    @normal_import_price_less_record = NormalImportPriceLessRecord.find(params[:id])
    @normal_import_price_less_record.destroy

    respond_to do |format|
      format.html { redirect_to normal_import_price_less_records_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/normal_import_price_less_records_helper.rb
module NormalImportPriceLessRecordsHelper
end

app/views/normal_import_price_less_records/_form.html.erb
<%= form_for(@normal_import_price_less_record) do |f| %>
  <% if @normal_import_price_less_record.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@normal_import_price_less_record.errors.count, "error") %> prohibited this normal_import_price_less_record from being saved:</h2>

      <ul>
      <% @normal_import_price_less_record.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :date_value %><br />
    <%= f.datetime_select :date_value %>
  </div>
  <div class="field">
    <%= f.label :declarations_number %><br />
    <%= f.text_field :declarations_number %>
  </div>
  <div class="field">
    <%= f.label :product_code %><br />
    <%= f.text_field :product_code %>
  </div>
  <div class="field">
    <%= f.label :product_number %><br />
    <%= f.number_field :product_number %>
  </div>
  <div class="field">
    <%= f.label :dollar_value %><br />
    <%= f.number_field :dollar_value %>
  </div>
  <div class="field">
    <%= f.label :first_legal_quantity %><br />
    <%= f.number_field :first_legal_quantity %>
  </div>
  <div class="field">
    <%= f.label :price %><br />
    <%= f.text_field :price %>
  </div>
  <div class="field">
    <%= f.label :actual_price_cap %><br />
    <%= f.text_field :actual_price_cap %>
  </div>
  <div class="field">
    <%= f.label :actual_price_floor %><br />
    <%= f.text_field :actual_price_floor %>
  </div>
  <div class="field">
    <%= f.label :national_average_price %><br />
    <%= f.text_field :national_average_price %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/normal_import_price_less_records/edit.html.erb
<h1>Editing normal_import_price_less_record</h1>

<%= render 'form' %>

<%= link_to 'Show', @normal_import_price_less_record %> |
<%= link_to 'Back', normal_import_price_less_records_path %>

app/views/normal_import_price_less_records/index.html.erb
<h1>Listing normal_import_price_less_records</h1>

<table>
  <tr>
    <th>Date value</th>
    <th>Declarations number</th>
    <th>Product code</th>
    <th>Product number</th>
    <th>Dollar value</th>
    <th>First legal quantity</th>
    <th>Price</th>
    <th>Actual price cap</th>
    <th>Actual price floor</th>
    <th>National average price</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @normal_import_price_less_records.each do |normal_import_price_less_record| %>
  <tr>
    <td><%= normal_import_price_less_record.date_value %></td>
    <td><%= normal_import_price_less_record.declarations_number %></td>
    <td><%= normal_import_price_less_record.product_code %></td>
    <td><%= normal_import_price_less_record.product_number %></td>
    <td><%= normal_import_price_less_record.dollar_value %></td>
    <td><%= normal_import_price_less_record.first_legal_quantity %></td>
    <td><%= normal_import_price_less_record.price %></td>
    <td><%= normal_import_price_less_record.actual_price_cap %></td>
    <td><%= normal_import_price_less_record.actual_price_floor %></td>
    <td><%= normal_import_price_less_record.national_average_price %></td>
    <td><%= link_to 'Show', normal_import_price_less_record %></td>
    <td><%= link_to 'Edit', edit_normal_import_price_less_record_path(normal_import_price_less_record) %></td>
    <td><%= link_to 'Destroy', normal_import_price_less_record, confirm: 'Are you sure?', method: :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Normal import price less record', new_normal_import_price_less_record_path %>

app/views/normal_import_price_less_records/new.html.erb
<h1>New normal_import_price_less_record</h1>

<%= render 'form' %>

<%= link_to 'Back', normal_import_price_less_records_path %>

app/views/normal_import_price_less_records/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Date value:</b>
  <%= @normal_import_price_less_record.date_value %>
</p>

<p>
  <b>Declarations number:</b>
  <%= @normal_import_price_less_record.declarations_number %>
</p>

<p>
  <b>Product code:</b>
  <%= @normal_import_price_less_record.product_code %>
</p>

<p>
  <b>Product number:</b>
  <%= @normal_import_price_less_record.product_number %>
</p>

<p>
  <b>Dollar value:</b>
  <%= @normal_import_price_less_record.dollar_value %>
</p>

<p>
  <b>First legal quantity:</b>
  <%= @normal_import_price_less_record.first_legal_quantity %>
</p>

<p>
  <b>Price:</b>
  <%= @normal_import_price_less_record.price %>
</p>

<p>
  <b>Actual price cap:</b>
  <%= @normal_import_price_less_record.actual_price_cap %>
</p>

<p>
  <b>Actual price floor:</b>
  <%= @normal_import_price_less_record.actual_price_floor %>
</p>

<p>
  <b>National average price:</b>
  <%= @normal_import_price_less_record.national_average_price %>
</p>


<%= link_to 'Edit', edit_normal_import_price_less_record_path(@normal_import_price_less_record) %> |
<%= link_to 'Back', normal_import_price_less_records_path %>